---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: virium-manual-pv
  labels:
    name: virium-manual
spec:
  storageClassName: virium
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: virium.csi.virer.net
    volumeHandle: virium-data-id
    volumeAttributes:
      targetPortal: "192.168.0.147:3260"
      portals: "[]"
      iqn: "iqn.2015-06.net.virer.virium.test:target1"
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"
