---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-csi-iscsiadm
  namespace: kube-system
data:
  iscsiadm: |
    #!/bin/sh
    if [ -x /host/sbin/iscsiadm ]; then
      chroot /host /sbin/iscsiadm "$@"
    elif [ -x /host/usr/local/sbin/iscsiadm ]; then
      chroot /host /usr/local/sbin/iscsiadm "$@"
    elif [ -x /host/bin/iscsiadm ]; then
      chroot /host /bin/iscsiadm "$@"
    elif [ -x /host/usr/local/bin/iscsiadm ]; then
      chroot /host /usr/local/bin/iscsiadm "$@"
    else
      chroot /host iscsiadm "$@"
    fi
---
kind: Secret
apiVersion: v1
metadata:
  creationTimestamp: null
  name: virium-creds
  namespace: kube-system
data:
  apiurl: aHR0cDovL3Zpcml1bS1hcGktZnFkbi5kb21haW4udGxkOjg3ODcK
  initiator: aXFuLjIwMjUtMDQubmV0LnZpcmVyLnZpcml1bS50ZXN0OnRhcmdldDE=
  api_username: dmlyaXVtX2FwaV91c2VybmFtZQ==
  api_password: dmlyaXVtX2FwaV9wYXNzd29yZA==
