---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virium-iscsiplugin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: virium